name: Update Tokens From Figma

on:
  repository_dispatch:
    types: [update-tokens]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create tokens file from Figma dispatch
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'tokens.json'
          json: ${{ github.event.client_payload.tokens }}
          dir: 'data'

      - name: Install dependencies
        run: npm ci

      - name: Transform tokens
        run: npm run global

      - name: Build tokens
        run: npm run build

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "build: tokens from Figma"
          add: "build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
